// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0pWPgIMNLK7amw_j4U2m8olWy1O4Kj4',
    appId: '1:203614101967:web:6c1c7abccb9d79adee72ba',
    messagingSenderId: '203614101967',
    projectId: 'foodhub-a1ec1',
    authDomain: 'foodhub-a1ec1.firebaseapp.com',
    storageBucket: 'foodhub-a1ec1.firebasestorage.app',
    measurementId: 'G-0MDY0F2RJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ch2__zgMVSS8MoNNBHQm8VpL25NJJ18',
    appId: '1:203614101967:android:bd9a87f7c873b72bee72ba',
    messagingSenderId: '203614101967',
    projectId: 'foodhub-a1ec1',
    storageBucket: 'foodhub-a1ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeSkVFH6deOUJs8tuLSQqk1RkauDKE4_c',
    appId: '1:203614101967:ios:aced7afd0f7cab1cee72ba',
    messagingSenderId: '203614101967',
    projectId: 'foodhub-a1ec1',
    storageBucket: 'foodhub-a1ec1.firebasestorage.app',
    iosBundleId: 'com.foodhub.foodhub',
  );
}
